### ISSUE TITLE
Setting up zkp fails to create verifier key for createPO

### ISSUE THREAD

**Issue by Perseverance** [ethereum-oasis/baseline#55]
## Expected Behavior
Following the documentation, and running `npm run setup` the script successfully generates the zk material for createMSA, but fails to do so for createPO. I expect both to work as per the documentation.

## Actual Behavior
CreateMSA goes through successfully, but createPO fails with the following found in the zkp container logs:
```
Error: export-verifier verifying key file not found
    at Object.exportVerifier (/app/node_modules/@eyblockchain/zokrates.js/lib/export-verifier.js:29:11)
    at _callee$ (/app/src/routes/generateKeys.js:30:20)
    at tryCatch (/app/node_modules/regenerator-runtime/runtime.js:45:40)
    at Generator.invoke [as _invoke] (/app/node_modules/regenerator-runtime/runtime.js:274:22)
    at Generator.prototype.(anonymous function) [as next] (/app/node_modules/regenerator-runtime/runtime.js:97:21)
    at asyncGeneratorStep (/app/src/routes/generateKeys.js:22:103)
    at _next (/app/src/routes/generateKeys.js:24:194)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
```

## Steps to Reproduce the Problem

Follow the steps for running the demo until step 4.

**Comment by Perseverance** [comment]
Trying to resolve it:
- Downgrading the dependency to zokrates 0.4.11 as per official https://github.com/EYBlockchain/zokrates.js/tree/master Zokrates.js docs

**Comment by Perseverance** [comment]
Resolved it via increasing my docker memory to 4GB. createPO ZK process takes at what I've seen 2,5GB RAM.
