### ISSUE TITLE
make deploy-contracts fails

### ISSUE THREAD

**Issue by j4ys0n** [ethereum-oasis/baseline#91]
## Expected Behavior
contracts should deploy successfully

## Actual Behavior
contract deployment fails

## Steps to Reproduce the Problem

  1. `make`
  1. `make deploy-contracts`

## Specifications

  - Version: latest
  - Platform: macOS 10.15, docker 2.2.0.4
  - Subsystem:

output from `make deploy-contracts`
```
✅  ERC1820Registry deployed: 0x48518130D429cbbfeaB451589804e3f06e771b22
✅  OrgRegistry deployed: 0x361cDE6eBCE28366d838F4Ec0E2E567EC79de58D
✅  BN256G2 library deployed: 0xF5eC22d79357f5F301A4B03481Df21D219231B62
✅  Verifier deployed: 0x36670e25a536496F889E732e53f21092A4e302A7
✅  Shield deployed: 0xe249E1Fb19fab52A406fa4dC62104269517199ea
✅  Assigned the deployer as the manager for OrgRegistry. TxHash: 0xb0b707b266c77d8cc45d3e215640e47eb93d2f878730b2fb4407b3097b3bbb22
✅  Set OrgRegistry as Interface Implementer for deployer. TxHash: 0xe57bf4d8f122e6bbd9b7160a7fa7dbd5dee6dc658a745d390740ce2becf63192
Could not retrieve Whisper ID. Check health of MESSENGER services: Error: socket hang up
    at connResetException (internal/errors.js:581:14)
    at Socket.socketOnEnd (_http_client.js:451:23)
    at Socket.emit (events.js:224:7)
    at endReadableNT (_stream_readable.js:1206:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'ECONNRESET',
  config: {
    url: 'http://messenger-buyer:4001/api/v1/identities',
    method: 'get',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'User-Agent': 'axios/0.19.2'
    },
    ...
    _currentUrl: 'http://messenger-buyer:4001/api/v1/identities'
  },
  response: undefined,
  isAxiosError: true,
  toJSON: [Function (anonymous)]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! radish-34@1.0.0 deploy: `docker-compose run --rm deploy sh deploy.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the radish-34@1.0.0 deploy script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jayson/.npm/_logs/2020-04-02T15_36_31_660Z-debug.log
make: *** [deploy-contracts] Error 1
```

I've tried this on two different machines. `make` completes successfully. `make deploy-contracts` gives the same error on both machines. between attempts i've run `make clean`, `docker system prune` then `make` again.

**Comment by bitwiseguy** [comment]
@j4ys0n Sorry for the issue. Can you share the output from `docker logs messenger-buyer`?

**Comment by j4ys0n** [comment]
Doh, this is my bad. I added auth to mongodb. Sorry about that!
