### ISSUE TITLE
Build Error: export-verifier verifying key file not found 

### ISSUE THREAD

**Issue by jeffprestes** [ethereum-oasis/baseline#94]
## Expected Behavior
*** Running setup for createPO ***
{"verificationKey":{"H":[["0x2d5f6d4b7d13b5cebd8d6cece9dbce5ecb04d3ea80217e0426c2b1d72c2d972d","0x02ff4a4667c3fead0b270277aba0fef1a8f2e94e85b160d19385c089ac7cf501"],["0x25ddb0f3266fc2b2efefa6247f24355a327353f6ccfb5ca9fb5ab1352370a21b","0x1c078f4b5447ef774133731e301b43a9c8657123409333efffa74486a86fb47f"]],"Galpha":["0x0d36fc5d69ce3f50ec40bb9d3540fb1d898a2f91d48932bf55cfcb304af635e3","0x1a555461b3ac218af5fca356d75b9d0eecce6bb8d44aab275141e1a980077a67"],"Hbeta":[["0x29a47d9266d3a915ba517cd2d099ef4872c568d86d69c63ff5fa55aa7a5f6284","0x1125edf840c07eda41a962f71f1e0d8b4c0052587c6b6918ebb3a267c43b6255"],["0x2d15aefb7f2a3374e28671f5b4b5dc1db80660656b16fd81953a6104a95b61ef","0x2e43d6f090a7402b948824568e69a956646a8ddc79eba4bfad65da4863663ce5"]],"Ggamma":["0x11cf0010dc05657a0933a3366efab90a055ef76c926af3c94cd79df0daace624","0x138c005e154787838b851afc869be363e089b2e3786c197c1a7a7f8023e2adcf"],"Hgamma":[["0x267470583b8333a4c8b81331d12d6badfd49c416810fd23006ec393f812c8a56","0x14321eed994c76846d2b8b532e7995d3cb76c022ab05af426a99e98a53076779"],["0x0cfcd3abdf0119481374bf209c71f7afcd8920b85de0e95294933ddd3c16c92a","0x23871104deb8a7c03efaf1ede048dd9f968b4602ea7f824a5c8d4aaa1e6f4143"]],"query":[["0x1a7251f3ac3930802d03eae0f4d8187a62bcf752b33cedd98defe74ddc07cd8f","0x06a13bbc659fae79a8e0ab7fa474d4ae451d42633116e42e17334ee21a847fc5"],["0x26620d77c65980fb18256ee17bc0e80adc30ddb4c54cd61154432d713889ea33","0x237af6ad935a45192f8a279e3543bca9b04aa547d16501c3c164c9ef38ad59c0"]]}}

## Actual Behavior
Error: export-verifier verifying key file not found<br>    at Object.exportVerifier (/app/node_modules/@eyblockchain/zokrates.js/lib/export-verifier.js:29:11)<br>    at _callee$ (/app/src/routes/generateKeys.js:30:20)<br>    at tryCatch (/app/node_modules/regenerator-runtime/runtime.js:45:40)<br>    at Generator.invoke [as _invoke] (/app/node_modules/regenerator-runtime/runtime.js:274:22)<br>    at Generator.prototype.(anonymous function) [as next] (/app/node_modules/regenerator-runtime/runtime.js:97:21)<br>    at asyncGeneratorStep (/app/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)<br>    at _next (/app/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)<br>    at processTicksAndRejections (internal/process/task_queues.js:86:5)

## Steps to Reproduce the Problem

  1. Follow readme steps until step 4
  2. runs npm run setup
  

## Specifications

  - Version: latest
  - Platform: MacOs 10.15.4
  - Subsystem: node -v -> v11.15.0 || npm -v 6.7.0

**Comment by jeffprestes** [comment]
Closing it was solved with suggestions at https://github.com/ethereum-oasis/baseline/issues/55
